# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Read The Elements of Statistical Learning book
description: >- # this means to ignore newlines until "baseurl:"
This is my note written when I read the book ["The Elements of Statistical Learning: Data Mining, Inference, and Prediction, Second Edition" by Trevor Hastie, Robert Tibshirani, and Jerome Friedman](https://www.amazon.com/Elements-Statistical-Learning-Prediction-Statistics/dp/0387848576)  .
baseurl: "/read_ml_book" # the subpath of the site
url: "https://tranktle.github.io" # the base hostname & protocol for the site
og_image: /assets/img/profile-pic.jpg
#google_analytics: "UA-121636368-3"

header:
  pages:
    - name: Home
      slug: /
    - name: About
    - name: Blog

footer:
  show_powered_by: true

  follow:
    - name: GitHub
      link: https://github.com/tranktle

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
